# Generated by Django 5.2 on 2025-05-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default='computer science', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='computer science', on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default='computer science', on_delete=django.db.models.deletion.CASCADE, to='teacher.topic'),
        ),
    ]
